description: 'Generated config'

prompts:
  - id: QuantumDataCollectorTool__prompt_task1
    label: QuantumDataCollectorTool__prompt_task1
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_task1
  - id: QuantumDataCollectorTool__prompt_task2
    label: QuantumDataCollectorTool__prompt_task2
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_task2
  - id: QuantumDataCollectorTool__prompt_task3
    label: QuantumDataCollectorTool__prompt_task3
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_task3
  - id: QuantumDataCollectorTool__prompt_task4
    label: QuantumDataCollectorTool__prompt_task4
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_task4
  - id: QuantumDataCollectorTool__prompt_extract_rubric
    label: QuantumDataCollectorTool__prompt_extract_rubric
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_extract_rubric
  - id: QuantumDataCollectorTool__prompt_transition_feedback
    label: QuantumDataCollectorTool__prompt_transition_feedback
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_transition_feedback
  - id: QuantumDataCollectorTool__prompt_extract_company_name
    label: QuantumDataCollectorTool__prompt_extract_company_name
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_extract_company_name
  - id: QuantumDataCollectorTool__prompt_auto_clarify
    label: QuantumDataCollectorTool__prompt_auto_clarify
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_auto_clarify
  - id: QuantumDataCollectorTool__prompt_clarification_decision
    label: QuantumDataCollectorTool__prompt_clarification_decision
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_clarification_decision
  - id: QuantumDataCollectorTool__prompt_ai_completion
    label: QuantumDataCollectorTool__prompt_ai_completion
    raw: exec:C:/Users/clord/AppData/Local/Programs/Python/Python311/python.exe -m promptfoo_tests.create_prompt exec_prompt --prompt QuantumDataCollectorTool__prompt_ai_completion

providers:

  - id: openai:claude-haiku-4-5
    config:
      apiBaseUrl: "{{ env.LITELLM_BASE_URL }}"
      apiKey: "{{ env.LITELLM_API_KEY }}"

tests:
  - file://test_cases/test-QuantumDataCollectorTool__prompt_task1.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_task2.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_task3.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_task4.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_extract_rubric.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_transition_feedback.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_extract_company_name.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_auto_clarify.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_clarification_decision.yaml
  - file://test_cases/test-QuantumDataCollectorTool__prompt_ai_completion.yaml

